<?php

namespace Proyecto\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRepository extends EntityRepository
{
    /**
     * Encuentra algunos datos del usuario indicado
     * @param $id el id del usuario
     */
    public function findById($id){


        $em = $this->getEntityManager();

        $consulta = $em->createQuery('
          SELECT u.username, u.nombres, u.apellidos
            FROM AdminBundle:Usuarios u
            WHERE u.id = :id
        ');

        $consulta->setParameter('id',$id);

        return $consulta->getResult();

    }
}
